# Generated by Django 5.2.13 on 2026-04-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologia', '0003_customer_created_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='alerts',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sales',
        ),
    ]
