# Generated by Django 5.0.4 on 2026-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologia', '0005_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('reliability_score', models.IntegerField(default=98)),
                ('avg_delivery_days', models.IntegerField(default=2)),
            ],
        ),
    ]
