# Generated by Django 5.0.4 on 2026-04-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologia', '0007_systemauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologia.invoice'),
        ),
        migrations.AddField(
            model_name='alert',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologia.product'),
        ),
    ]
